Log collect no juju ssh
juju/autopilot-log-collector pull request #3
Opened 2017-01-14 02:42 UTC by blackboxsw

https://bugs.launchpad.net/juju/+bug/1473069  is cripliing our log-collector on system-test runs. More than 1/3 of the system test runs are missing logs from various units making triage difficult.

This quick pass against log-collector is to allow us to obtain the properly reported unit ip addresses from juju status and just directly ssh using juju's juju_id_rsa private key.

This avoids various ssh hostname key errors or intermittently referencing internal IP addresses which cause collect-logs to bail on timeouts which there is no response from the juju unit's internal ips.

2017-01-17 19:37 UTC, fginther requested changes
Outside of 'make test' not passing (which I would like to see fixed), these comments are minor or nitpicks.

2017-01-17 19:37 UTC, fginther commented on collect-logs
> +                os.path.expanduser("~"), ".local", "share", "juju")
Please add a comment that this is assuming juju2 and juju1 will not work with this. I don't think we need to make juju 1 work, just note it.

2017-01-17 19:37 UTC, fginther commented on collect-logs
> +    return status["machines"]["0"]["dns-name"]
There is also `status["machines"]["0"]["ip-addresses"][0]`, but `"dns-name"` looks like it has the same value in our case.

2017-01-17 19:37 UTC, fginther commented on collect-logs
> +        ",".join([u[0] for u in units])))
Shouldn't this be: `[u.name for u in units]`?

2017-01-17 19:37 UTC, fginther commented on collect-logs
> +             juju_ssh=False):
nitpick. I think it makes more sense to default `juju_ssh=True` here and then specify it as False when calling `get_juju()` in `"__main__"`

2017-01-17 23:07 UTC, blackboxsw commented on collect-logs
> +             juju_ssh=False):
fixed

2017-01-17 23:09 UTC, blackboxsw commented on collect-logs
> +        ",".join([u[0] for u in units])))
fixed. yeah it can be referenced either way equivalently, but this was an oversight.

2017-01-17 23:10 UTC, blackboxsw commented on collect-logs
> +    return status["machines"]["0"]["dns-name"]
Agreed, I couldn't decide which to pull and wasn't certain when the "ip-addresses" list got longer than 1.

2017-01-17 23:33 UTC, fginther approved these changes

2017-01-18 04:33 UTC, fginther reviewed
Nice addition. Would be nice if there was a complementary set of test methods for the juju_ssh=True path. However, these are implicitly tested via other test methods so I'm not going to hold up this PR.

2017-01-18 16:30 UTC, merged